//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignWay.DeliveryManager.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForeignWay.DeliveryManager.StringResources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddUserControl_Add {
            get {
                return ResourceManager.GetString("AddUserControl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddUserControl_Cancel {
            get {
                return ResourceManager.GetString("AddUserControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AddUserControl_Password {
            get {
                return ResourceManager.GetString("AddUserControl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUserControl_Title {
            get {
                return ResourceManager.GetString("AddUserControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AddUserControl_UserName {
            get {
                return ResourceManager.GetString("AddUserControl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        public static string AddUserControl_UserType {
            get {
                return ResourceManager.GetString("AddUserControl_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string NewOrderView_Title {
            get {
                return ResourceManager.GetString("NewOrderView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersView_Title {
            get {
                return ResourceManager.GetString("OrdersView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SettingsView_User_Header {
            get {
                return ResourceManager.GetString("SettingsView_User_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term:.
        /// </summary>
        public static string SettingsView_User_SearchTerm {
            get {
                return ResourceManager.GetString("SettingsView_User_SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Shell_NavigateBack {
            get {
                return ResourceManager.GetString("Shell_NavigateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SingInView_LogIn {
            get {
                return ResourceManager.GetString("SingInView_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SingInView_Password {
            get {
                return ResourceManager.GetString("SingInView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string SingInView_UserName {
            get {
                return ResourceManager.GetString("SingInView_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Credentials!.
        /// </summary>
        public static string SingInView_WrongCredentials {
            get {
                return ResourceManager.GetString("SingInView_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string UserSettingsControl_AddUser {
            get {
                return ResourceManager.GetString("UserSettingsControl_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string UserSettingsControl_Remove {
            get {
                return ResourceManager.GetString("UserSettingsControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove the current user!.
        /// </summary>
        public static string UserSettingsControl_RemoveCurrentUser_ErrorMessage {
            get {
                return ResourceManager.GetString("UserSettingsControl_RemoveCurrentUser_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UserSettingsControl_RemoveCurrentUser_ErrorTitle {
            get {
                return ResourceManager.GetString("UserSettingsControl_RemoveCurrentUser_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserSettingsControl_UserName {
            get {
                return ResourceManager.GetString("UserSettingsControl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserSettingsControl_UserType {
            get {
                return ResourceManager.GetString("UserSettingsControl_UserType", resourceCulture);
            }
        }
    }
}
